### ISSUE TITLE
Bureau: Cube maze security booth survey flickers between interactions with the vidbot

### ISSUE THREAD

**Issue by rparnas** [elasota/scummvm#133]
- Talk to security vidbot
- Turn in the form without filling it out
- Talk to security vidbot again
- Form flashes on screen before 'handing it to you' video clip

or 

- Talk to security vidbot
- Fill out form
- Turn in form
- Talk to security vidbot again
- Fill it out again
- Form flashes away before 'taking it from you' video clip plays

Issue not present on Win retail.

Tested against:
* Win retail on Win98 SE
* [MTROPOLIS: Add auto-save triggers for Obsidian Immediate Action clock… · elasota/scummvm@dcb19fb](https://github.com/elasota/scummvm/commit/dcb19fbfbbf50c08f793c4fef1bac3eaf225f5cd)

**Comment by elasota** [comment]
Fixed by 57ee73f33f852ee063c08990f0ad171e8210c51e

**Comment by elasota** [comment]
OK, seems like what's happening here is the vidbot's play range is being set to a new range, but if the play range is behind the current timestamp then it gets set to the end of the play range, which is probably wrong, and it doesn't send a play event to the video until a 500ms timer expires.

Other vidbots are probably affected too but we've just never noticed because the end of their play ranges isn't so obviously different from the first frame.

**Comment by elasota** [comment]
Fixed by f94e15d65385eb3e696cb1df00a53dfccea00a63
