### ISSUE TITLE
Spider: Test side area control panel

### ISSUE THREAD

**Issue by elasota** [elasota/scummvm#35]

**Comment by rparnas** [comment]
Tested levers reachable by the gondola on the west side in the main area. Seeing the animations for all four levers requires multiple saves because the level immediately ends upon completing all four puzzles.

Only found #137. 

Tested against:
* Win retail on Win98 SE
* [MTROPOLIS: Fix incorrect mToon mouse collision frame offset handling · elasota/scummvm@87aacc6](https://github.com/elasota/scummvm/commit/87aacc623b751d5b186dd2a32f0976c7231d7097)
